### ISSUE TITLE
error en la función crear base de trabajo

### ISSUE THREAD

**Issue by lorevir** [dnme-minturdep/evyth#15]
`Error in serialize(object, connection = NULL, ascii = ascii, version = serializeVersion) : 
  no puede asignarse buffer`

**Comment by pablotis** [comment]
Resuelto [acá](https://github.com/dnme-minturdep/evyth/commit/9ddfc0eb936c56cab386816cbdc8fd5f015267b6). Problema con la variable gasto_pc cuando no es numérica
