### ISSUE TITLE
error en obtener_ipc()

### ISSUE THREAD

**Issue by TuQmano** [dnme-minturdep/evyth#19]
maquinas virtuales Windows falla en levantar `xls`  en ejemplo de `obtener_ipc()` 

`libxls error: Unable to open file`

https://github.com/r-universe/dnme-minturdep/actions/runs/4620978054/jobs/8171921039#step:8:973

**Comment by jpruiznicolini** [comment]
Solucionado en https://github.com/dnme-minturdep/evyth/commit/97093ae9fc1b5f7c8cf2f352d46ddf6d5de8d724 con `'\dontrun' `del ejemplo.
