### ISSUE TITLE
Resolver último check de metadata del paquete

### ISSUE THREAD

**Issue by pablotis** [dnme-minturdep/evyth#7]
![imagen](https://user-images.githubusercontent.com/30708601/191146016-70fb84e7-14e4-4fb2-b3ed-fc18c137e7d5.png)

**Comment by TuQmano** [comment]
── R CMD check results ──── evyth 0.0.0.9001 ────
Duration: 26.1s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

**Comment by TuQmano** [comment]
Resuelto en https://github.com/dnme-minturdep/evyth/commit/c93c51f3e6252d8b4f8932237ab898b077f1985b
